# Étape 1 : Construction avec une image complète
FROM node:18 AS builder

# Crée et positionne le répertoire de travail
WORKDIR /backend

# Copie les fichiers package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Installe les dépendances de production
RUN npm install

# Copie le reste des fichiers du projet
COPY . .

# Installer nodemon pour le hot reload
RUN npm install -g @nestjs/cli nodemon

EXPOSE 4000

# Définit la commande par défaut pour lancer l'application
CMD ["npm", "run", "start:dev"]